### ISSUE TITLE
Command line Args

### ISSUE THREAD

**Issue by Ared0** [overclokk/py-youtube-downloader#1]
Accettare arguments da riga di comando, ad esempio:

`python <script>.py --video <url> --cut sec:sec`

**Comment by overclokk** [comment]
Si potrebbe fare, se sai già come fai pure una pull.
Per la url ci sarebbe anche (commentato) il modo di copiarlo dalla clipboard del OS.
Altrimenti anche qui un file esterno con url.

**Comment by Ared0** [comment]
Yep sto cominciando a lavorarci.

Per quanto riguarda la clipboard, il package che hai usato non funziona su Linux (che io uso 😂). Al limite implementiamo dei flag appositi tipo `--file <nome-file>.txt` o `--clipboard`.

**Comment by overclokk** [comment]
Si, è vero, ora ricordo.
Ad ogni modo (clipboard a parte) stavo anche dockerizzando l'app così tutti possono eseguirla (senza clipboard ovviamente).

**Comment by overclokk** [comment]
Ho fatto un piccolo refactoring per il formato del timestamp, ora è `[HH:]MM:SS,[HH:]MM:SS` come nei file che uso la stessa funzione per convertire l'orario in secondi cos' diventa più gestibile.

**Comment by Ared0** [comment]
Ci sta, cosi è molto più comodo 👍

Poi bisognerebbe implementare qualcosa per convalidare gli input, ma sinceramente per ora mi sembra molto low priority come cosa

**Comment by overclokk** [comment]
Sto ragionando sui comandi vari e qui alcune considerazioni:

Direi che un sistema a "step" sia più immediato anche se "più lento", 1 fai questo, 2 fai quello ecc
Il parametro per i timestamp dovrebbe essere opzionale perché:

Se lancio l'app con solo l'url del video dovrebbe scaricare senza bloccarmi (se volessi solo il video senza clip)
Se lancio l'app con anche i timestamp va bene come ora quindi taglio clip
Se lancio l'app senza argomenti dovrebbe mostrare gli step successivi da compiere e qui si può:

`py app/index.py`
` > Inserisci video url:`

[1] - Create clip from CLI argument _(qui la mancanza della s è voluta)_
[2] - Create clips from video description
[3] - Create clips from file

**Comment by Ared0** [comment]
Ho implementato il menu, domani faccio la PR che devo dargli una ripulita prima.

**Comment by overclokk** [comment]
Ottimo, ora ci do un occhio e poi mergio
